config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => redirect("/users/sign_in")

  # Projects
  get 'projects', to: 'projects#index', as: 'projects'  
  post 'projects', to: 'projects#create'
  get 'projects/new', to: 'projects#new', as: 'new_project'
  get 'projects/:id', to: 'projects#show', as: 'project'
  patch 'projects/:id', to: 'projects#update'
  delete 'projects/:id', to: 'projects#destroy'
  get 'projects/:id/edit', to: 'projects#edit', as: 'edit_project'
  
  post 'projects/:id/add_user', to: 'projects#add_user_to_projects', as: 'add_user_project'
  post 'projects/:id/remove_user', to: 'projects#remove_users_from_project', as: 'remove_user_project'
  post 'projects/:id/transfer_manager', to: 'projects#transfer_manager_of_projects', as: 'transfer_manager'

  #permissions for projects
  post 'projects/:id/add_user_can_edit_project', to: 'projects#add_users_to_can_edit_projects', as: 'add_user_can_edit_project'
  post 'projects/:id/remove_user_can_edit_project', to: 'projects#remove_users_from_can_edit_projects', as: 'remove_user_can_edit_project'

  post 'projects/:id/add_user_can_delete_project', to: 'projects#add_users_to_can_delete_projects', as: 'add_user_can_delete_project'
  post 'projects/:project_id/boards/:id/remove_user_can_delete_project', to: 'projects#remove_users_from_can_delete_projects', as: 'remove_user_can_delete_project'

  post 'projects/:id/add_user_can_assign_users_project', to: 'projects#add_users_to_can_assign_users_to_projects', as: 'add_user_can_assign_users_project'
  post 'projects/:id/remove_user_can_assign_users_project', to: 'projects#remove_users_from_can_assign_users_to_projects', as: 'remove_user_can_assign_users_project'

  post 'projects/:id/add_user_can_remove_users_project', to: 'projects#add_users_to_can_remove_users_from_projects', as: 'add_user_can_remove_users_project'
  post 'projects/:id/remove_user_can_remove_users_project', to: 'projects#remove_users_from_can_remove_users_from_projects', as: 'remove_user_can_remove_users_project'

  # Boards routes
  get 'projects/:project_id/boards', to: 'boards#index', as: 'boards'  
  post 'projects/:project_id/boards', to: 'boards#create'
  get 'projects/:project_id/boards/new', to: 'boards#new', as: 'new_board'
  get 'projects/:project_id/boards/:id', to: 'boards#show', as: 'board'
  patch 'projects/:project_id/boards/:id', to: 'boards#update'  
  delete 'projects/:project_id/boards/:id', to: 'boards#destroy', as: 'delete_board'
  get 'projects/:project_id/boards/:id/edit', to: 'boards#edit', as: 'edit_board'

  post 'projects/:project_id/boards/:id/transfer_manager', to: 'boards#transfer_manager_of_boards', as: 'transfer_manager_board'

  post 'projects/:project_id/boards/:id/add_user_board', to: 'boards#add_user_to_boards', as: 'add_user_board'
  post 'projects/:project_id/boards/:id/remove_user_board', to: 'boards#remove_users_from_board', as: 'remove_user_board'

  #permissions for boards
  post 'projects/:project_id/boards/:id/add_user_can_edit_board', to: 'boards#add_users_to_can_edit_boards', as: 'add_user_can_edit_board'
  post 'projects/:project_id/boards/:id/remove_user_can_edit_board', to: 'boards#remove_users_from_can_edit_boards', as: 'remove_user_can_edit_board'

  post 'projects/:project_id/boards/:id/add_user_can_delete_board', to: 'boards#add_users_to_can_delete_boards', as: 'add_user_can_delete_board'
  post 'projects/:project_id/boards/:id/remove_user_can_delete_board', to: 'boards#remove_users_from_can_delete_boards', as: 'remove_user_can_delete_board'

  post 'projects/:project_id/boards/:id/add_user_can_assign_users_board', to: 'boards#add_users_to_can_assign_users_to_boards', as: 'add_user_can_assign_users_board'
  post 'projects/:project_id/boards/:id/remove_user_can_assign_users_board', to: 'boards#remove_users_from_can_assign_users_to_boards', as: 'remove_user_can_assign_users_board'

  post 'projects/:project_id/boards/:id/add_user_can_remove_users_board', to: 'boards#add_users_to_can_remove_users_from_boards', as: 'add_user_can_remove_users_board'
  post 'projects/:project_id/boards/:id/remove_user_can_remove_users_board', to: 'boards#remove_users_from_can_remove_users_from_boards', as: 'remove_user_can_remove_users_board'


  # Categories routes
  get 'boards/:board_id/categories/new',                                  to: 'categories#new',     as: 'new_category'
  post 'projects/:project_id/boards/:board_id/categories',                to: 'categories#create',  as: 'create_category'
  get 'categories/:category_id/edit',                                     to: 'categories#edit',    as: 'edit_category'
  patch 'projects/:project_id/boards/:board_id/categories/:category_id',  to: 'categories#update',  as: 'update_category'
  delete 'categories/:category_id',                                       to: 'categories#destroy', as: 'delete_category'
  get 'categories/:category_id',                                          to: 'categories#show',    as: 'show_category'
  post 'categories/:category_id/transfer_manager', to: 'categories#transfer_manager_of_cats', as: 'transfer_manager_cat'

  post 'categories/:category_id/add_user', to: 'categories#add_user_to_category', as: 'add_user_category'
  post 'categories/:category_id/remove_user', to: 'categories#remove_users_from_category', as: 'remove_user_category'

  #permissions for categories
  post 'categories/:category_id/add_user_can_edit_category', to: 'categories#add_users_to_can_edit_categories', as: 'add_user_can_edit_category'
  post 'categories/:category_id/remove_user_can_edit_category', to: 'categories#remove_users_from_can_edit_categories', as: 'remove_user_can_edit_category'

  post 'categories/:category_id/add_user_can_delete_category', to: 'categories#add_users_to_can_delete_categories', as: 'add_user_can_delete_category'
  post 'categories/:category_id/remove_user_can_delete_category', to: 'categories#remove_users_from_can_delete_categories', as: 'remove_user_can_delete_category'

  post 'categories/:category_id/add_user_can_assign_users_category', to: 'categories#add_users_to_can_assign_users_to_categories', as: 'add_user_can_assign_users_category'
  post 'categories/:category_id/remove_user_can_assign_users_category', to: 'categories#remove_users_from_can_assign_users_to_categories', as: 'remove_user_can_assign_users_category'

  post 'categories/:category_id/add_user_can_remove_users_category', to: 'categories#add_users_to_can_remove_users_from_categories', as: 'add_user_can_remove_users_category'
  post 'categories/:category_id/remove_user_can_remove_users_category', to: 'categories#remove_users_from_can_remove_users_from_categories', as: 'remove_user_can_remove_users_category'


  # Tasks routes
  get 'categories/:category_id/new',  to: 'tasks#new',      as: 'new_task'
  get 'tasks/:task_id',               to: 'tasks#show',     as: 'show_task'
  post 'categories/:category_id',     to: 'tasks#create',   as: 'create_task'
  delete 'tasks/:task_id',            to: 'tasks#delete',   as: 'delete_task'
  get 'tasks/:task_id/edit',          to: 'tasks#edit',     as: 'edit_task'
  patch 'tasks/:task_id',             to: 'tasks#update',   as: 'update_task'
  post 'tasks/:task_id/transfer_manager', to: 'tasks#transfer_manager_of_tasks', as: 'transfer_manager_task'

  post 'task/:task_id/add_user', to: 'tasks#add_user_to_task', as: 'add_user_task'
  post 'task/:task_id/remove_user', to: 'tasks#remove_users_from_task', as: 'remove_user_task'
  post 'task/:task_id/move_task', to: 'tasks#transfer_tasks_to_diff_category', as: 'move_task'

  #permission for tasks
  post 'task/:task_id/add_user_can_edit_task', to: 'tasks#add_users_to_can_edit_tasks', as: 'add_user_can_edit_task'
  post 'task/:task_id/remove_user_can_edit_task', to: 'tasks#remove_users_from_can_edit_tasks', as: 'remove_user_can_edit_task'

  post 'task/:task_id/add_user_can_delete_task', to: 'tasks#add_users_to_can_delete_tasks', as: 'add_user_can_delete_task'
  post 'task/:task_id/remove_user_can_delete_task', to: 'tasks#remove_users_from_can_delete_tasks', as: 'remove_user_can_delete_task'

  post 'task/:task_id/add_user_can_assign_users_task', to: 'tasks#add_users_to_can_assign_users_to_tasks', as: 'add_user_can_assign_users_task'
  post 'task/:task_id/remove_user_can_assign_users_task', to: 'tasks#remove_users_from_can_assign_users_to_tasks', as: 'remove_user_can_assign_users_task'

  post 'task/:task_id/add_user_can_remove_users_task', to: 'tasks#add_users_to_can_remove_users_from_tasks', as: 'add_user_can_remove_users_task'
  post 'task/:task_id/remove_user_can_remove_users_task', to: 'tasks#remove_users_from_can_remove_users_from_tasks', as: 'remove_user_can_remove_users_task'

  # Comments routes
  post 'tasks/:task_id/comments',     to: 'comments#create',  as: 'create_comment'
  delete 'comments/:comment_id',      to: 'comments#delete',  as: 'delete_comment'
  get 'comments/:comment_id/edit',          to: 'comments#edit',     as: 'edit_comment'
  patch 'comments/:comment_id',         to: 'comments#update',         as: 'update_comment'
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id             :bigint           not null, primary key
#  description    :string
#  due_date       :string
#  estimated_work :integer
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  category_id    :bigint
#  user_id        :bigint
#
# Indexes
#
#  index_tasks_on_category_id  (category_id)
#  index_tasks_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Task < ApplicationRecord


    # Has many assocation with category
    belongs_to(
        :category,
        class_name: 'Category',
        foreign_key: 'category_id',
        inverse_of: :tasks
    )

    # Has many association with user for manager association
    belongs_to(
        :user,
        class_name: 'User',
        foreign_key: 'user_id',
        inverse_of: :tasks
    )

    #Has many association with comment
    has_many(
        :comments,
        class_name: 'Comment',
        foreign_key: 'task_id',
        inverse_of: :task,
        dependent: :destroy
    )

    # Many to Many association with user for permissons

    has_many :task_assignments, dependent: :destroy
    has_many :assigned_users, :through => :task_assignments, :source => :user

    has_many :task_can_edit_assignements, dependent: :destroy
    has_many :can_edit_users, :through => :task_can_edit_assignements, :source => :user

    has_many :task_can_delete_assignements, dependent: :destroy
    has_many :can_delete_users, :through => :task_can_delete_assignements, :source => :user

    has_many :task_can_assign_users_assignements, dependent: :destroy
    has_many :can_assign_users, :through => :task_can_assign_users_assignements, :source => :user

    has_many :task_can_remove_users_assignements, dependent: :destroy
    has_many :can_remove_users, :through =>  :task_can_remove_users_assignements, :source => :user
    
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= bootstrap_form_with model: @task, method: :patch, url: update_task_path(@task), local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.text_field :estimated_work %>
  <%= f.text_field :due_date %>
  <%= f.submit %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', show_category_path(@task.category), class: 'btn btn-primary' %>
</p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= bootstrap_form_with model: @task, method: :post, url: create_task_path(@category), local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.text_field :estimated_work %>
  <%= f.text_field :due_date %>
  <%= f.submit %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', show_category_path(@category), class: 'btn btn-primary' %>
</p>


app/views/tasks/show.html.erb
<h1><b>Task:</b> <%=@task.name%></h1>
<p><b>Owner:</b> <%=@task.user.name%></p>

<p><b>Due:</b> <%=@task.due_date%></p>
<p><b>Estimated Work:</b> <%=@task.estimated_work%></p>
<p><b>Description:</b> <%=@task.description%></p>
<% if  @task.user == current_user || current_user.is_admin == true %>
  <p><b>Move to Different Category:</b> 
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Category List
        <span class="caret"></span></button>
            <ul class="dropdown-menu">
            <% @categories.each do |category|%>
                <li><%= category.name %> </li>
                <li> <%= link_to 'Select', move_task_path(@task, category, category_id: category.id, task_id: @task.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                    <hr class="rounded">
            <%end%>
            </ul>
      </div>
  </p>
<% end %>

<h4>Comments</h4>
<table>
  <tbody>
    <%@task.comments.each do |comment|%>
      <tr>
        <td style="color:blue">(<%=comment.updated_at.strftime("%d/%m/%y")%>) <%=comment.user.name%>: <i><%=comment.comment%></i></td>
        <%if current_user == comment.user || current_user.is_admin%>
          <td>
            <%=link_to '🗑️', delete_comment_path(comment), method: :delete%> | 
            <%=link_to '✏️', edit_comment_path(comment)%>
          </td>
        <%end%>
      </tr>
    <%end%>
  </tbody>
</table>

<%= bootstrap_form_with model: Comment.new, method: :post, url: create_comment_path(@task), local: true do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit %>
<% end %>


<div><h1></h2></div>
<div>
  <h5><strong>Users Assigned to <%= @task.name%></strong></h5>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Add Users
                            <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                <% @users.each do |user|%>
                                    <li><%= user.name %> </li>
                                    <li> <%= link_to 'Select', add_user_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                        <hr class="rounded">
                                <%end%>
                                </ul>
                        </div>
<% if current_user == @task.user || current_user.is_admin == true %>
  <th> 
    <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Transfer Manager Position
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
      Current Manager: <%= @task.user.name%>
      <hr>
        <% @users.each do |user|%>
          <%if user != @task.user %>
            <li><%= user.name %> </li>
            <li> <%= link_to 'Select', transfer_manager_task_path(user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
            <hr class="rounded">
          <%end%>
        <%end%>
      </ul>
    </div>
  </th>
<%end%>
                    </th>
                </tr>
            </thead>

                
            <tbody>
                <%@task.assigned_users.each do |assigned_user|%>
                    <tr>
                        <td><%= assigned_user.name %></td>
                        <td><%= assigned_user.email %></td>
                        <td><%= link_to 'Remove User', remove_user_task_path(@task, assigned_user, id: @task.id, user_id: assigned_user.id), method: :post, class: "btn btn-outline-primary btn-sm"%></td>
                    </tr>
                <%end%>
            </tbody>

          <tfoot><!-- this footnote is used to manage assigning permissions for the task -->
        <% if @project.user == current_user || @board.user == current_user || @category.user == current_user || @task.user == current_user || current_user.is_admin == true %>
             <tr>
                 
                 <td>PERMISSIONS</td>
                 
             </tr>
             <tr>
                 <td>can edit task</td>
                 <td>
                     <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can edit
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', add_user_can_edit_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
 
                 <td>
                     <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can edit
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @task.can_edit_users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', remove_user_can_edit_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
             </tr>
             <tr>
                 <td>can delete task</td>
                 <td>
                  <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can delete
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', add_user_can_delete_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 
                 </td>
                 <td>
                     <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can delete
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @task.can_delete_users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', remove_user_can_delete_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
             </tr>
             <tr>
                 <td>can assign users to task</td>
                 <td>
                     <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can assign users
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', add_user_can_assign_users_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
                 <td>
                     <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can assign users
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @task.can_assign_users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', remove_user_can_assign_users_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
             </tr>
             <tr>
                 <td>can delete users from task</td>
                 <td>
                      <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can remove users
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', add_user_can_remove_users_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
                 <td>
                      <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can remove users
                                 <span class="caret"></span></button>
                                     <ul class="dropdown-menu">
                                     <% @task.can_remove_users.each do |user|%>
                                         <li><%= user.name %> </li>
                                         <li> <%= link_to 'Select', remove_user_can_remove_users_task_path(@task, user, id: @task.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                             <hr class="rounded">
                                     <%end%>
                                     </ul>
                             </div>
                 </td>
             </tr>
             
             <% end %>
         </tfoot>
        </table>
        
</div>

<p class="mt-3">
  <%= link_to 'Back', show_category_path(@task.category), class: 'btn btn-primary' %>
</p>