config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => redirect("/users/sign_in")

  # Projects
  get 'projects', to: 'projects#index', as: 'projects'  
  post 'projects', to: 'projects#create'
  get 'projects/new', to: 'projects#new', as: 'new_project'
  get 'projects/:id', to: 'projects#show', as: 'project'
  patch 'projects/:id', to: 'projects#update'
  delete 'projects/:id', to: 'projects#destroy'
  get 'projects/:id/edit', to: 'projects#edit', as: 'edit_project'
  
  post 'projects/:id/add_user', to: 'projects#add_user_to_projects', as: 'add_user_project'
  post 'projects/:id/remove_user', to: 'projects#remove_users_from_project', as: 'remove_user_project'
  post 'projects/:id/transfer_manager', to: 'projects#transfer_manager_of_projects', as: 'transfer_manager'

  #permissions for projects
  post 'projects/:id/add_user_can_edit_project', to: 'projects#add_users_to_can_edit_projects', as: 'add_user_can_edit_project'
  post 'projects/:id/remove_user_can_edit_project', to: 'projects#remove_users_from_can_edit_projects', as: 'remove_user_can_edit_project'

  post 'projects/:id/add_user_can_delete_project', to: 'projects#add_users_to_can_delete_projects', as: 'add_user_can_delete_project'
  post 'projects/:project_id/boards/:id/remove_user_can_delete_project', to: 'projects#remove_users_from_can_delete_projects', as: 'remove_user_can_delete_project'

  post 'projects/:id/add_user_can_assign_users_project', to: 'projects#add_users_to_can_assign_users_to_projects', as: 'add_user_can_assign_users_project'
  post 'projects/:id/remove_user_can_assign_users_project', to: 'projects#remove_users_from_can_assign_users_to_projects', as: 'remove_user_can_assign_users_project'

  post 'projects/:id/add_user_can_remove_users_project', to: 'projects#add_users_to_can_remove_users_from_projects', as: 'add_user_can_remove_users_project'
  post 'projects/:id/remove_user_can_remove_users_project', to: 'projects#remove_users_from_can_remove_users_from_projects', as: 'remove_user_can_remove_users_project'

  # Boards routes
  get 'projects/:project_id/boards', to: 'boards#index', as: 'boards'  
  post 'projects/:project_id/boards', to: 'boards#create'
  get 'projects/:project_id/boards/new', to: 'boards#new', as: 'new_board'
  get 'projects/:project_id/boards/:id', to: 'boards#show', as: 'board'
  patch 'projects/:project_id/boards/:id', to: 'boards#update'  
  delete 'projects/:project_id/boards/:id', to: 'boards#destroy', as: 'delete_board'
  get 'projects/:project_id/boards/:id/edit', to: 'boards#edit', as: 'edit_board'

  post 'projects/:project_id/boards/:id/transfer_manager', to: 'boards#transfer_manager_of_boards', as: 'transfer_manager_board'

  post 'projects/:project_id/boards/:id/add_user_board', to: 'boards#add_user_to_boards', as: 'add_user_board'
  post 'projects/:project_id/boards/:id/remove_user_board', to: 'boards#remove_users_from_board', as: 'remove_user_board'

  #permissions for boards
  post 'projects/:project_id/boards/:id/add_user_can_edit_board', to: 'boards#add_users_to_can_edit_boards', as: 'add_user_can_edit_board'
  post 'projects/:project_id/boards/:id/remove_user_can_edit_board', to: 'boards#remove_users_from_can_edit_boards', as: 'remove_user_can_edit_board'

  post 'projects/:project_id/boards/:id/add_user_can_delete_board', to: 'boards#add_users_to_can_delete_boards', as: 'add_user_can_delete_board'
  post 'projects/:project_id/boards/:id/remove_user_can_delete_board', to: 'boards#remove_users_from_can_delete_boards', as: 'remove_user_can_delete_board'

  post 'projects/:project_id/boards/:id/add_user_can_assign_users_board', to: 'boards#add_users_to_can_assign_users_to_boards', as: 'add_user_can_assign_users_board'
  post 'projects/:project_id/boards/:id/remove_user_can_assign_users_board', to: 'boards#remove_users_from_can_assign_users_to_boards', as: 'remove_user_can_assign_users_board'

  post 'projects/:project_id/boards/:id/add_user_can_remove_users_board', to: 'boards#add_users_to_can_remove_users_from_boards', as: 'add_user_can_remove_users_board'
  post 'projects/:project_id/boards/:id/remove_user_can_remove_users_board', to: 'boards#remove_users_from_can_remove_users_from_boards', as: 'remove_user_can_remove_users_board'


  # Categories routes
  get 'boards/:board_id/categories/new',                                  to: 'categories#new',     as: 'new_category'
  post 'projects/:project_id/boards/:board_id/categories',                to: 'categories#create',  as: 'create_category'
  get 'categories/:category_id/edit',                                     to: 'categories#edit',    as: 'edit_category'
  patch 'projects/:project_id/boards/:board_id/categories/:category_id',  to: 'categories#update',  as: 'update_category'
  delete 'categories/:category_id',                                       to: 'categories#destroy', as: 'delete_category'
  get 'categories/:category_id',                                          to: 'categories#show',    as: 'show_category'
  post 'categories/:category_id/transfer_manager', to: 'categories#transfer_manager_of_cats', as: 'transfer_manager_cat'

  post 'categories/:category_id/add_user', to: 'categories#add_user_to_category', as: 'add_user_category'
  post 'categories/:category_id/remove_user', to: 'categories#remove_users_from_category', as: 'remove_user_category'

  #permissions for categories
  post 'categories/:category_id/add_user_can_edit_category', to: 'categories#add_users_to_can_edit_categories', as: 'add_user_can_edit_category'
  post 'categories/:category_id/remove_user_can_edit_category', to: 'categories#remove_users_from_can_edit_categories', as: 'remove_user_can_edit_category'

  post 'categories/:category_id/add_user_can_delete_category', to: 'categories#add_users_to_can_delete_categories', as: 'add_user_can_delete_category'
  post 'categories/:category_id/remove_user_can_delete_category', to: 'categories#remove_users_from_can_delete_categories', as: 'remove_user_can_delete_category'

  post 'categories/:category_id/add_user_can_assign_users_category', to: 'categories#add_users_to_can_assign_users_to_categories', as: 'add_user_can_assign_users_category'
  post 'categories/:category_id/remove_user_can_assign_users_category', to: 'categories#remove_users_from_can_assign_users_to_categories', as: 'remove_user_can_assign_users_category'

  post 'categories/:category_id/add_user_can_remove_users_category', to: 'categories#add_users_to_can_remove_users_from_categories', as: 'add_user_can_remove_users_category'
  post 'categories/:category_id/remove_user_can_remove_users_category', to: 'categories#remove_users_from_can_remove_users_from_categories', as: 'remove_user_can_remove_users_category'


  # Tasks routes
  get 'categories/:category_id/new',  to: 'tasks#new',      as: 'new_task'
  get 'tasks/:task_id',               to: 'tasks#show',     as: 'show_task'
  post 'categories/:category_id',     to: 'tasks#create',   as: 'create_task'
  delete 'tasks/:task_id',            to: 'tasks#delete',   as: 'delete_task'
  get 'tasks/:task_id/edit',          to: 'tasks#edit',     as: 'edit_task'
  patch 'tasks/:task_id',             to: 'tasks#update',   as: 'update_task'
  post 'tasks/:task_id/transfer_manager', to: 'tasks#transfer_manager_of_tasks', as: 'transfer_manager_task'

  post 'task/:task_id/add_user', to: 'tasks#add_user_to_task', as: 'add_user_task'
  post 'task/:task_id/remove_user', to: 'tasks#remove_users_from_task', as: 'remove_user_task'
  post 'task/:task_id/move_task', to: 'tasks#transfer_tasks_to_diff_category', as: 'move_task'

  #permission for tasks
  post 'task/:task_id/add_user_can_edit_task', to: 'tasks#add_users_to_can_edit_tasks', as: 'add_user_can_edit_task'
  post 'task/:task_id/remove_user_can_edit_task', to: 'tasks#remove_users_from_can_edit_tasks', as: 'remove_user_can_edit_task'

  post 'task/:task_id/add_user_can_delete_task', to: 'tasks#add_users_to_can_delete_tasks', as: 'add_user_can_delete_task'
  post 'task/:task_id/remove_user_can_delete_task', to: 'tasks#remove_users_from_can_delete_tasks', as: 'remove_user_can_delete_task'

  post 'task/:task_id/add_user_can_assign_users_task', to: 'tasks#add_users_to_can_assign_users_to_tasks', as: 'add_user_can_assign_users_task'
  post 'task/:task_id/remove_user_can_assign_users_task', to: 'tasks#remove_users_from_can_assign_users_to_tasks', as: 'remove_user_can_assign_users_task'

  post 'task/:task_id/add_user_can_remove_users_task', to: 'tasks#add_users_to_can_remove_users_from_tasks', as: 'add_user_can_remove_users_task'
  post 'task/:task_id/remove_user_can_remove_users_task', to: 'tasks#remove_users_from_can_remove_users_from_tasks', as: 'remove_user_can_remove_users_task'

  # Comments routes
  post 'tasks/:task_id/comments',     to: 'comments#create',  as: 'create_comment'
  delete 'comments/:comment_id',      to: 'comments#delete',  as: 'delete_comment'
  get 'comments/:comment_id/edit',          to: 'comments#edit',     as: 'edit_comment'
  patch 'comments/:comment_id',         to: 'comments#update',         as: 'update_comment'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_projects_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Project < ApplicationRecord

    # Has many association with Board
    has_many(
        :boards, 
        class_name: 'Board', 
        foreign_key: 'project_id',
        inverse_of: :project, 
        dependent: :destroy
    )

    # Has many association with user for manager association
    belongs_to(
        :user, 
        class_name: 'User',
        foreign_key: 'user_id',
        inverse_of: :projects
    )

    # Many to many association with user for projectprivleges

    has_many :project_assignements, dependent: :destroy
    has_many :assigned_users, :through => :project_assignements, :source => :user
    
    has_many :project_can_edit_assignements, dependent: :destroy
    has_many :can_edit_users, :through => :project_can_edit_assignements, :source => :user

    has_many :project_can_delete_assignements, dependent: :destroy
    has_many :can_delete_users, :through => :project_can_delete_assignements, :source => :user

    has_many :project_can_assign_users_assignements, dependent: :destroy
    has_many :can_assign_users, :through => :project_can_assign_users_assignements, :source => :user

    has_many :project_can_remove_users_assignements, dependent: :destroy
    has_many :can_remove_users, :through => :project_can_remove_users_assignements, :source => :user
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= bootstrap_form_with model: @project, url: project_path, method: :patch, local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.submit %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', projects_path(@project), class: 'btn btn-outline-secondary' %>
</p>

app/views/projects/index.html.erb
<h1></h1>
<!-- Displays welcome message to the current user and includes admin beside their name if they are an admin -->
<h1 style="background-color:DimGray ; text-align:center; color: White"> Welcome <%= current_user.name%>!
 <% if current_user.is_admin == true %> (Admin) <%end%> </h1>

<h2 style="float:right"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary' %> </h1>

<h3>Current Projects:</h1>

<table class="table table-hover">

  <thead class="thead-dark">
    <tr>
      <th>Name of Project:</th>
      <th>Manager of Project:</th>
      <th>Users Assigned to Project </th>
      <th>Interact with Your Projects:</th>
    </tr>
  </thead>
  
    <tbody>
      <!-- Stores all the project ids that the user is involved in to corresponding arrays, show the project they are involved with. -->
        <%ids = Array.new([])%>
        
        <%@projects.each do |pro|  %>
          <%if pro.assigned_users.include?(current_user) || pro.user == current_user || current_user.is_admin == true%>
              <%ids << pro.id %>
            <%end%>
        <% end %>

        <%@boards.each do |board|%>
          <%project = board.project.id%>
          <%if board.assigned_users.include?(current_user) || board.user == current_user || current_user.is_admin == true%>
            <%ids << project %>
          <%end%>
        <%end%>
        
        <%@categories.each do |cat|%>
          <%project = cat.board.project.id%>
          <%if cat.assigned_users.include?(current_user) || cat.user == current_user || current_user.is_admin == true%>
            <%ids << project %>
          <%end%>
        <%end%>

        <%@tasks.each do |task|%>
          <%project = task.category.board.project.id%>
          <%if task.assigned_users.include?(current_user) || task.user == current_user || current_user.is_admin == true%>
            <%ids << project %>
          <%end%>
        <%end%>
        
        <!-- Removes any repetetive projects from project id list -->
        <%ids_uniq = ids.uniq%>
        <!-- Displays project info if the user is the creator, an admin, or assigned to the project (or its contents) -->
        <%@projects.each do |project|%>
          <%if ids_uniq.include?(project.id)  %>
          <tr>
                <td><%= project.name %></td>
                <td><%= project.user.name %></td>

                <!-- Dropdown menu that displays each user assigned to the project -->
                <td><div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Dropdown
                      <span class="caret"></span></button>
                      <ul class="dropdown-menu">
                        <%project.assigned_users.each do |assigned_user|%>
                        <li><%= assigned_user.email %> </li>
                          <hr class="rounded">
                        <%end%>
                      </ul>
                    </div> </td>
                <td>
                    <!-- Only allows the creator of the project or an admin to edit/destroy it -->
                      <%= link_to 'show', project_path(project), class: 'btn btn-secondary btn-sm' %>
                    <% if project.user == current_user || current_user.is_admin == true || project.can_edit_users.include?(current_user) == true %> 
                  |   <%= link_to 'edit', edit_project_path(project), class: 'btn btn-secondary btn-sm' %> 
                    <%end%>
                    <% if project.user == current_user || current_user.is_admin == true || project.can_delete_users.include?(current_user) == true %>
                  |    <%= link_to 'destroy', project_path(project), method: :delete, class: 'btn btn-secondary btn-sm' %>
                    <%end%>
                </td>
          </tr>
          <%end%>
        <%end%>
    </tbody>
</table>

<p>
  <div><%= link_to 'New Project', new_project_path, class: "btn btn-secondary" %></div>
</p>

app/views/projects/new.html.erb
<h1>Create New Project</h1>

<%= bootstrap_form_with model: @project, url: projects_path, method: :post, local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.submit %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', projects_path(@project), class: 'btn btn-outline-secondary' %>
</p>