config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => redirect("/users/sign_in")

  # Projects
  get 'projects', to: 'projects#index', as: 'projects'  
  post 'projects', to: 'projects#create'
  get 'projects/new', to: 'projects#new', as: 'new_project'
  get 'projects/:id', to: 'projects#show', as: 'project'
  patch 'projects/:id', to: 'projects#update'
  delete 'projects/:id', to: 'projects#destroy'
  get 'projects/:id/edit', to: 'projects#edit', as: 'edit_project'
  
  post 'projects/:id/add_user', to: 'projects#add_user_to_projects', as: 'add_user_project'
  post 'projects/:id/remove_user', to: 'projects#remove_users_from_project', as: 'remove_user_project'
  post 'projects/:id/transfer_manager', to: 'projects#transfer_manager_of_projects', as: 'transfer_manager'

  #permissions for projects
  post 'projects/:id/add_user_can_edit_project', to: 'projects#add_users_to_can_edit_projects', as: 'add_user_can_edit_project'
  post 'projects/:id/remove_user_can_edit_project', to: 'projects#remove_users_from_can_edit_projects', as: 'remove_user_can_edit_project'

  post 'projects/:id/add_user_can_delete_project', to: 'projects#add_users_to_can_delete_projects', as: 'add_user_can_delete_project'
  post 'projects/:project_id/boards/:id/remove_user_can_delete_project', to: 'projects#remove_users_from_can_delete_projects', as: 'remove_user_can_delete_project'

  post 'projects/:id/add_user_can_assign_users_project', to: 'projects#add_users_to_can_assign_users_to_projects', as: 'add_user_can_assign_users_project'
  post 'projects/:id/remove_user_can_assign_users_project', to: 'projects#remove_users_from_can_assign_users_to_projects', as: 'remove_user_can_assign_users_project'

  post 'projects/:id/add_user_can_remove_users_project', to: 'projects#add_users_to_can_remove_users_from_projects', as: 'add_user_can_remove_users_project'
  post 'projects/:id/remove_user_can_remove_users_project', to: 'projects#remove_users_from_can_remove_users_from_projects', as: 'remove_user_can_remove_users_project'

  # Boards routes
  get 'projects/:project_id/boards', to: 'boards#index', as: 'boards'  
  post 'projects/:project_id/boards', to: 'boards#create'
  get 'projects/:project_id/boards/new', to: 'boards#new', as: 'new_board'
  get 'projects/:project_id/boards/:id', to: 'boards#show', as: 'board'
  patch 'projects/:project_id/boards/:id', to: 'boards#update'  
  delete 'projects/:project_id/boards/:id', to: 'boards#destroy', as: 'delete_board'
  get 'projects/:project_id/boards/:id/edit', to: 'boards#edit', as: 'edit_board'

  post 'projects/:project_id/boards/:id/transfer_manager', to: 'boards#transfer_manager_of_boards', as: 'transfer_manager_board'

  post 'projects/:project_id/boards/:id/add_user_board', to: 'boards#add_user_to_boards', as: 'add_user_board'
  post 'projects/:project_id/boards/:id/remove_user_board', to: 'boards#remove_users_from_board', as: 'remove_user_board'

  #permissions for boards
  post 'projects/:project_id/boards/:id/add_user_can_edit_board', to: 'boards#add_users_to_can_edit_boards', as: 'add_user_can_edit_board'
  post 'projects/:project_id/boards/:id/remove_user_can_edit_board', to: 'boards#remove_users_from_can_edit_boards', as: 'remove_user_can_edit_board'

  post 'projects/:project_id/boards/:id/add_user_can_delete_board', to: 'boards#add_users_to_can_delete_boards', as: 'add_user_can_delete_board'
  post 'projects/:project_id/boards/:id/remove_user_can_delete_board', to: 'boards#remove_users_from_can_delete_boards', as: 'remove_user_can_delete_board'

  post 'projects/:project_id/boards/:id/add_user_can_assign_users_board', to: 'boards#add_users_to_can_assign_users_to_boards', as: 'add_user_can_assign_users_board'
  post 'projects/:project_id/boards/:id/remove_user_can_assign_users_board', to: 'boards#remove_users_from_can_assign_users_to_boards', as: 'remove_user_can_assign_users_board'

  post 'projects/:project_id/boards/:id/add_user_can_remove_users_board', to: 'boards#add_users_to_can_remove_users_from_boards', as: 'add_user_can_remove_users_board'
  post 'projects/:project_id/boards/:id/remove_user_can_remove_users_board', to: 'boards#remove_users_from_can_remove_users_from_boards', as: 'remove_user_can_remove_users_board'


  # Categories routes
  get 'boards/:board_id/categories/new',                                  to: 'categories#new',     as: 'new_category'
  post 'projects/:project_id/boards/:board_id/categories',                to: 'categories#create',  as: 'create_category'
  get 'categories/:category_id/edit',                                     to: 'categories#edit',    as: 'edit_category'
  patch 'projects/:project_id/boards/:board_id/categories/:category_id',  to: 'categories#update',  as: 'update_category'
  delete 'categories/:category_id',                                       to: 'categories#destroy', as: 'delete_category'
  get 'categories/:category_id',                                          to: 'categories#show',    as: 'show_category'
  post 'categories/:category_id/transfer_manager', to: 'categories#transfer_manager_of_cats', as: 'transfer_manager_cat'

  post 'categories/:category_id/add_user', to: 'categories#add_user_to_category', as: 'add_user_category'
  post 'categories/:category_id/remove_user', to: 'categories#remove_users_from_category', as: 'remove_user_category'

  #permissions for categories
  post 'categories/:category_id/add_user_can_edit_category', to: 'categories#add_users_to_can_edit_categories', as: 'add_user_can_edit_category'
  post 'categories/:category_id/remove_user_can_edit_category', to: 'categories#remove_users_from_can_edit_categories', as: 'remove_user_can_edit_category'

  post 'categories/:category_id/add_user_can_delete_category', to: 'categories#add_users_to_can_delete_categories', as: 'add_user_can_delete_category'
  post 'categories/:category_id/remove_user_can_delete_category', to: 'categories#remove_users_from_can_delete_categories', as: 'remove_user_can_delete_category'

  post 'categories/:category_id/add_user_can_assign_users_category', to: 'categories#add_users_to_can_assign_users_to_categories', as: 'add_user_can_assign_users_category'
  post 'categories/:category_id/remove_user_can_assign_users_category', to: 'categories#remove_users_from_can_assign_users_to_categories', as: 'remove_user_can_assign_users_category'

  post 'categories/:category_id/add_user_can_remove_users_category', to: 'categories#add_users_to_can_remove_users_from_categories', as: 'add_user_can_remove_users_category'
  post 'categories/:category_id/remove_user_can_remove_users_category', to: 'categories#remove_users_from_can_remove_users_from_categories', as: 'remove_user_can_remove_users_category'


  # Tasks routes
  get 'categories/:category_id/new',  to: 'tasks#new',      as: 'new_task'
  get 'tasks/:task_id',               to: 'tasks#show',     as: 'show_task'
  post 'categories/:category_id',     to: 'tasks#create',   as: 'create_task'
  delete 'tasks/:task_id',            to: 'tasks#delete',   as: 'delete_task'
  get 'tasks/:task_id/edit',          to: 'tasks#edit',     as: 'edit_task'
  patch 'tasks/:task_id',             to: 'tasks#update',   as: 'update_task'
  post 'tasks/:task_id/transfer_manager', to: 'tasks#transfer_manager_of_tasks', as: 'transfer_manager_task'

  post 'task/:task_id/add_user', to: 'tasks#add_user_to_task', as: 'add_user_task'
  post 'task/:task_id/remove_user', to: 'tasks#remove_users_from_task', as: 'remove_user_task'
  post 'task/:task_id/move_task', to: 'tasks#transfer_tasks_to_diff_category', as: 'move_task'

  #permission for tasks
  post 'task/:task_id/add_user_can_edit_task', to: 'tasks#add_users_to_can_edit_tasks', as: 'add_user_can_edit_task'
  post 'task/:task_id/remove_user_can_edit_task', to: 'tasks#remove_users_from_can_edit_tasks', as: 'remove_user_can_edit_task'

  post 'task/:task_id/add_user_can_delete_task', to: 'tasks#add_users_to_can_delete_tasks', as: 'add_user_can_delete_task'
  post 'task/:task_id/remove_user_can_delete_task', to: 'tasks#remove_users_from_can_delete_tasks', as: 'remove_user_can_delete_task'

  post 'task/:task_id/add_user_can_assign_users_task', to: 'tasks#add_users_to_can_assign_users_to_tasks', as: 'add_user_can_assign_users_task'
  post 'task/:task_id/remove_user_can_assign_users_task', to: 'tasks#remove_users_from_can_assign_users_to_tasks', as: 'remove_user_can_assign_users_task'

  post 'task/:task_id/add_user_can_remove_users_task', to: 'tasks#add_users_to_can_remove_users_from_tasks', as: 'add_user_can_remove_users_task'
  post 'task/:task_id/remove_user_can_remove_users_task', to: 'tasks#remove_users_from_can_remove_users_from_tasks', as: 'remove_user_can_remove_users_task'

  # Comments routes
  post 'tasks/:task_id/comments',     to: 'comments#create',  as: 'create_comment'
  delete 'comments/:comment_id',      to: 'comments#delete',  as: 'delete_comment'
  get 'comments/:comment_id/edit',          to: 'comments#edit',     as: 'edit_comment'
  patch 'comments/:comment_id',         to: 'comments#update',         as: 'update_comment'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_categories_on_board_id  (board_id)
#  index_categories_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (user_id => users.id)
#
class Category < ApplicationRecord

    # Has many association with board
    belongs_to(
        :board,
        class_name: 'Board',
        foreign_key: 'board_id',
        inverse_of: :categories
    )

    # Has many association with user for manager association
    belongs_to(
        :user,
        class_name: 'User',
        foreign_key: 'user_id',
        inverse_of: :categories
    )

    # Has many association with task
    has_many(
        :tasks, 
        class_name: 'Task',
        foreign_key: 'category_id',
        inverse_of: :category, 
        dependent: :destroy
    )

    # Many to Many association with user for categoryprivleges

    has_many :category_assignments, dependent: :destroy
    has_many :assigned_users, :through => :category_assignments, :source => :user

    has_many :category_can_edit_assignements, dependent: :destroy
    has_many :can_edit_users, :through => :category_can_edit_assignements, :source => :user

    has_many :category_can_delete_assignements, dependent: :destroy
    has_many :can_delete_users, :through => :category_can_delete_assignements, :source => :user

    has_many :category_can_assign_users_assignements, dependent: :destroy
    has_many :can_assign_users, :through => :category_can_assign_users_assignements, :source => :user

    has_many :category_can_remove_users_assignements, dependent: :destroy
    has_many :can_remove_users, :through => :category_can_remove_users_assignements, :source => :user
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= bootstrap_form_with model: @category, method: :patch, url: update_category_path(@project, @board, @category), local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.submit %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', board_path(@project, @board), class: 'btn btn-primary' %>
</p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= bootstrap_form_with model: @category, method: :post, url: create_category_path(@project, @board), local: true do |f| %>

  <%= f.text_field :name %>
  <%= f.submit %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', board_path(@project, @board), class: 'btn btn-primary' %>
</p>


app/views/categories/show.html.erb
<h1>Category: <%=@category.name%></h1>
<p><p>
<table class="table" style="table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Task</th>
            <th>Due Date</th>
            <th>Owner</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <%@category.tasks.each do |task|%>
        <tr>
            <td><%=task.name%></td>
            <td><%=task.due_date%></td>
            <td><%=task.user.name%></td>
            <td>
                <%=link_to 'Show', show_task_path(task)%> | 
                <%=link_to 'Edit', edit_task_path(task)%> | 
                <%=link_to 'Delete', delete_task_path(task), method: :delete%>
            </td>
        </tr>
    <%end%>
    </tbody>
</table>


<div><h1></h2></div>
<div>
  <h5><strong>Users Assigned to <%= @category.name%></strong></h5>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Add Users
                            <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                <% @users.each do |user|%>
                                    <li><%= user.name %> </li>
                                    <li> <%= link_to 'Select', add_user_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                        <hr class="rounded">
                                <%end%>
                                </ul>
                        </div>
                          <% if current_user == @category.user || current_user.is_admin == true %>
                        <th> 
                            <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Transfer Manager Position
                                <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    Current Manager: <%= @category.user.name%>
                                      <hr>
                                    <% @users.each do |user|%>
                                        
                                            <li><%= user.name %> </li>
                                            <li> <%= link_to 'Select', transfer_manager_cat_path(user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                        
                                    <%end%>
                                </ul>
                            </div>
                        </th>
            <%end%>
                    </th>
                </tr>
            </thead>


            <tbody>
                <%@category.assigned_users.each do |assigned_user|%>
                    <tr>
                        <td><%= assigned_user.name %></td>
                        <td><%= assigned_user.email %></td>
                        <td><%= link_to 'Remove User', remove_user_category_path(@category, assigned_user, id: @category.id, user_id: assigned_user.id), method: :post, class: "btn btn-outline-primary btn-sm"%></td>
                    </tr>
                <%end%>
            </tbody>

            <tfoot><!-- this footnote is used to manage assigning permissions for the category -->
       <% if @category.user == current_user || current_user.is_admin == true || @board.user == current_user || @project.user == current_user %>
            <tr>
                <td>PERMISSIONS</td>
            </tr>
            <tr>
                <td>can edit category</td>
                <td>
                    <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can edit
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', add_user_can_edit_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>

                <td>
                    <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can edit
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @category.can_edit_users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', remove_user_can_edit_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>
            </tr>
            <tr>
                <td>can delete category</td>
                <td>
                 <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can delete
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', add_user_can_delete_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                
                </td>
                <td>
                    <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can delete
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @category.can_delete_users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', remove_user_can_delete_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>
            </tr>
            <tr>
                <td>can assign users to category</td>
                <td>
                    <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can assign users
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', add_user_can_assign_users_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>
                <td>
                    <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can assign users
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @category.can_assign_users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', remove_user_can_assign_users_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>
            </tr>
            <tr>
                <td>can delete users from category</td>
                <td>
                     <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to add user to can remove users
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', add_user_can_remove_users_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>
                <td>
                     <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">dropdown to remove user from can remove users
                                <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                    <% @category.can_remove_users.each do |user|%>
                                        <li><%= user.name %> </li>
                                        <li> <%= link_to 'Select', remove_user_can_remove_users_category_path(@category, user, id: @category.id, user_id: user.id), method: :post, class: "btn btn-outline-primary btn-sm"%> </li>
                                            <hr class="rounded">
                                    <%end%>
                                    </ul>
                            </div>
                </td>
            </tr>
            <% end %>
        </tfoot>

        </table>

</div>

<p class="mt-3">
  <%= link_to 'Back', board_path(@category.board.project, @category.board), class: 'btn btn-primary' %>
  <%= link_to 'New Task', new_task_path(@category), class: 'btn btn-primary' %>
</p>